mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090

proxies: []   # сюда workflow вставит все сервера

proxy-groups:
  - name: 🚀 Auto-Select
    type: url-test
    proxies: []                # workflow подставит имена всех прокси
    url: http://www.gstatic.com/generate_204
    interval: 300

  - name: 🌍 Global
    type: select
    proxies:
      - 🚀 Auto-Select
      - DIRECT
      # workflow добавит сюда имена всех прокси

  - name: 🛑 Direct
    type: select
    proxies:
      - DIRECT

rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - MATCH,🚀 Auto-Select
